# Mandatory settings

blog_theme: dark
name: Gustave Rousselet
paginate: 25
url: https://gustaver.github.io


# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
local_fonts: false # Change to true if you wish to use local fonts
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: false # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  github: gustaver # Add your GitHub handle
  linkedin: gustaverousselet # Add your LinkedIn handle
  email: gustave.rousselet@icloud.com # Add your Email address
  spotify: superlardman # Add your Spotify handle
files:
  cv: cv.pdf # CV filename under files/

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: posts/:slug
